// import localFont from 'next/font/local';
"use client"
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import { AnimatePresence } from 'framer-motion';
import { usePathname } from 'next/navigation';
import BoxTransition from './components/BoxTransition'

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }, { children: React,ReactNode }) {
  const pathname = usePathname(); // Call the hook with parentheses

  return (
    <html lang='en'>
      <body>
        <Navbar />
        <AnimatePresence mode="wait">
        <BoxTransition key={pathname} />
          {children}
        </AnimatePresence>
        <Footer />
      </body>
    </html>
  );
}
